CUDA_VISIBLE_DEVICES=5 python test_xtal2dos.py \
    --concat_comp '' \
    --model 'e3nn' \
    --xtal2dos-loss-type 'KL' \
    --label_scaling 'normalized_sum' \
    --data_src 'binned_dos_128' \
    --trainset_subset_ratio 1.0 \
    --xtal2dos-label-dim 128 \
    --sche cosine \
    --opt adam \
    --lr 2e-3 \
    --warmup 300 \
    --T0 100 \
    --T_mult 1 \
    --eta_min 1e-4 \
    --num-epochs 200 \
    --c_epochs 50 \
    --batch-size 128 \
    --graph_dropout 0.2 \
    --dec_dropout 0.0 \
    --dec_in_dim 256 \
    --temp 1.0 \
    --sum_scale 1. \
    --step_interval 30 \
    --lambda_scale 1.0 \
    --lambda_factor 1.0 \
    --accum_step 1 \
    --clip 1e-2 \
    --weight_decay 0. \
    --rate_decay 2. \
    --d_model 512 \
    --dec_layers 6 \
    --h 8 \
    --check-point-path \
    e3nn_edos
